"""
treeforge/script_writer.py
--------------------------
Generates a self-contained Python script that recreates the entire
folder/file structure — no TreeForge installation required.

Usage:
    from treeforge.parser import parse_tree
    from treeforge.script_writer import write_script

    paths  = parse_tree(raw_text)
    script = write_script(paths)                  # returns str
    write_script(paths, output_path="create.py")  # also saves to disk
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List, Optional

from treeforge.parser import ParsedPath, split_dirs_and_files


# ---------------------------------------------------------------------------
# Default content per file type
# ---------------------------------------------------------------------------

def _default_content_expr(filename: str, comment: str = "") -> str:
    """Return a Python repr() expression for the file's starter content."""
    name = filename.lower()

    if name == "readme.md":
        stem = Path(filename).stem.replace("-", " ").replace("_", " ").title()
        return repr(f"# {stem}\n\nAdd description here.\n")

    if name == "requirements.txt":
        return repr("# Add your project dependencies here\n")

    if name in {".env.example", ".env.sample"}:
        return repr(
            "# Copy this file to .env and fill in real values.\n"
            "# NEVER commit the real .env file.\n\n"
            "# API_KEY=your_api_key_here\n"
        )

    if name == ".gitignore":
        return repr("__pycache__/\n*.pyc\n*.pyo\n.env\n.venv/\nvenv/\ndist/\nbuild/\n")

    if name.endswith(".ipynb"):
        nb = json.dumps({
            "cells": [],
            "metadata": {
                "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                "language_info": {"name": "python", "version": "3.10.0"},
            },
            "nbformat": 4,
            "nbformat_minor": 5,
        }, indent=2)
        return repr(nb)

    if name.endswith(".json"):
        return repr("{}\n")

    if name.endswith(".py"):
        doc = comment if comment else filename
        return repr(f'"""\n{doc}\n"""\n')

    if name.endswith(".csv"):
        return repr("")

    return "None"


# ---------------------------------------------------------------------------
# Block builders  (each returns plain Python lines, 4-space indented)
# ---------------------------------------------------------------------------

def _dir_block(parsed: ParsedPath) -> str:
    path = parsed.full_path.rstrip("/")
    return (
        f'    (base / "{path}").mkdir(parents=True, exist_ok=True)\n'
        f'    print("  \U0001f4c1 {path}")\n'
    )


def _file_block(parsed: ParsedPath) -> str:
    content_expr = _default_content_expr(parsed.name, parsed.comment)
    lines = [
        f'    # {parsed.full_path}',
        f'    _p = base / "{parsed.full_path}"',
        f'    _p.parent.mkdir(parents=True, exist_ok=True)',
        f'    if not _p.exists() or overwrite:',
    ]
    if content_expr == "None":
        lines.append('        _p.touch()')
    else:
        lines.append(f'        _p.write_text({content_expr}, encoding="utf-8")')
    lines += [
        '        created.append(str(_p.relative_to(base)))',
        '        print(f"  \u2713 {_p.relative_to(base)}")',
        '    else:',
        '        skipped.append(str(_p.relative_to(base)))',
        '        print(f"  \u2013 skipped: {_p.relative_to(base)}")',
        '',
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_script(
    paths: List[ParsedPath],
    project_name: str = "project",
    output_path: Optional[str] = None,
) -> str:
    """Generate a standalone Python script string (and optionally save it)."""
    dirs, files = split_dirs_and_files(paths)

    dir_section  = "    # ── Directories ──────────────────────────────────────\n"
    dir_section += "".join(_dir_block(d) for d in dirs)

    file_section  = "    # ── Files ────────────────────────────────────────────\n"
    file_section += "".join(_file_block(f) for f in files)

    script = "\n".join([
        "#!/usr/bin/env python3",
        '"""',
        "Auto-generated by TreeForge \U0001f333",
        f"Project  : {project_name}",
        f"Contents : {len(dirs)} directories, {len(files)} files",
        "",
        "Usage:",
        "    python create_structure.py",
        "    python create_structure.py /path/to/destination",
        "    python create_structure.py --overwrite",
        '"""',
        "",
        "import sys",
        "from pathlib import Path",
        "",
        "",
        "def create(base_dir: str = \".\", overwrite: bool = False) -> None:",
        "    base = Path(base_dir).resolve()",
        "    base.mkdir(parents=True, exist_ok=True)",
        "    created: list = []",
        "    skipped: list = []",
        "    print(f\"\\n\U0001f333 TreeForge \u2014 {base}\\n\")",
        "",
        dir_section,
        file_section,
        "    print(\"\\n\" + \"\u2500\" * 48)",
        "    print(f\"  \u2705 {len(created)} files created  |  {len(skipped)} skipped\")",
        "    print(\"\u2500\" * 48 + \"\\n\")",
        "",
        "",
        "if __name__ == \"__main__\":",
        "    _args = [a for a in sys.argv[1:] if not a.startswith(\"--\")]",
        "    _flags = sys.argv[1:]",
        "    create(_args[0] if _args else \".\", \"--overwrite\" in _flags)",
        "",
    ])

    if output_path:
        Path(output_path).write_text(script, encoding="utf-8")

    return script
